config/routes.rb
Rails.application.routes.draw do
  resources :concerts
  resources :meetings
  resources :pins
  devise_for :users
  root "concerts#index"

  get "about" => "pages#about"

end

app/models/concert.rb
class Concert < ActiveRecord::Base
     extend TimeSplitter::Accessors
     split_accessor :start_time, date_format: "%B %e , %Y"
end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  before_action :set_concert, only: [:show, :edit, :update, :destroy]

  # GET /concerts
  # GET /concerts.json
  def index
    @concerts = Concert.all
  end

  # GET /concerts/1
  # GET /concerts/1.json
  def show
  end

  # GET /concerts/new
  def new
    @concert = Concert.new
  end

  # GET /concerts/1/edit
  def edit
  end

  # POST /concerts
  # POST /concerts.json
  def create
    @concert = Concert.new(concert_params)

    respond_to do |format|
      if @concert.save
        format.html { redirect_to @concert, notice: 'Concert was successfully created.' }
        format.json { render :show, status: :created, location: @concert }
      else
        format.html { render :new }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /concerts/1
  # PATCH/PUT /concerts/1.json
  def update
    respond_to do |format|
      if @concert.update(concert_params)
        format.html { redirect_to @concert, notice: 'Concert was successfully updated.' }
        format.json { render :show, status: :ok, location: @concert }
      else
        format.html { render :edit }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concerts/1
  # DELETE /concerts/1.json
  def destroy
    @concert.destroy
    respond_to do |format|
      format.html { redirect_to concerts_url, notice: 'Concert was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_concert
      @concert = Concert.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def concert_params
      params.require(:concert).permit(:name, :city, :venue, :start_time, :media)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end 
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.build
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.build(pin_params)

    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.' 
    else
      render :new 
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.' 
    else
      render :edit 
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy

    @pin.destroy
    redirect_to pins_url, notice: 'Pin was successfully destroyed.' 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find_by(id: params[:id])
      redirect_to pins_path, notice: "Pin doesn't exist" if @pin.nil?
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/concerts/_form.html.erb
<%= form_for(@concert, html: {class: 'form-horizontal', style: 'margin-top: 20px'}) do |f| %>
  <% if @concert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@concert.errors.count, "error") %> prohibited this concert from being saved:</h2>

      <ul>
      <% @concert.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label "Artist:", class: 'col-sm-1 control-label' %>
    <div class="col-sm-3">
      <%= f.text_field :name, class: 'form-control input-sm'%>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label "City:", class: 'col-sm-1 control-label' %>
    <div class="col-sm-3">
      <%= f.text_field :city, class: 'form-control input-sm'%>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label "Venue:", class: 'col-sm-1 control-label' %>
    <div class="col-sm-3">
      <%= f.text_field :venue, class: 'form-control input-sm'%>
    </div>
  </div>
  <div class="field form-group">
      <%= f.label "BANGER:", class: 'col-sm-1 control-label' %>
      <div class="col-sm-3">
        <%= f.text_field :media, class: 'form-control input-sm'%>
      </div>
    </div>
  <div class="field form-group">
    <%= f.label "Date:", class: 'col-sm-1 control-label' %>
    <div class="col-sm-4" style="margin-top:7px">
      <%= f.datetime_select :start_time, class: 'form-control'%>
    </div>
  </div>
  <div class="actions form-group" style="margin-top:20px">
    <div class="col-sm-10">
      <%= f.submit class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/concerts/edit.html.erb
<h1>Edit Concert Details</h1>

<%= render 'form' %>

<%= link_to 'Show', @concert %> |
<%= link_to 'Cancel', concerts_path %>

app/views/concerts/index.html.erb
<div class="jumbotron center">
	<h1>The BANGERS Concert Calendar!</h1>
    <%= month_calendar events: @concerts do |date, concerts| %>
      <%= date %>

      <% concerts.each do |concert| %>
        <div>
          <%= concert.name %>
        </div>
      <% end %>
    <% end %>
</div>

<h1>All Concerts</h1>
<% if @concerts.length > 0 %>
  <table class="table" style="margin-bottom:30px">
    <thead>
      <tr>
        <th>Artist</th>
        <th>City</th>
        <!-- <th>Venue</th> -->
        <th>Date</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% sortedConcerts = @concerts.sort { |a,b| a.start_time <=> b.start_time } %>
      <% sortedConcerts.each do |concert| %>
        <tr>
          <td><%= link_to concert.name, concert %></td>
          <td><%= concert.city %></td>
          <!-- <td><%= concert.venue %></td> -->
          <td><%= concert.start_time_date %></td>
          <td>
            <%= link_to 'Edit', edit_concert_path(concert) %>
            <%= link_to 'Remove', concert, method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p style="margin-bottom:30px">No Concerts Yet! Add one to the calendar by clicking "Add Concert" in the Navigation up top!</p>
<% end %>

app/views/concerts/new.html.erb
<h1>New Concert</h1>

<%= render 'form' %>

<%= link_to 'Back', concerts_path %>

app/views/concerts/show.html.erb
<h1>Concert Details</h1>

<p>
  <strong>Artist:</strong>
  <%= @concert.name %>
</p>

<p>
  <strong>City:</strong>
  <%= @concert.city %>
</p>

<p>
  <strong>Venue:</strong>
  <%= @concert.venue %>
</p>

<p>
  <strong>Date:</strong>
  <%= @concert.start_time_date %>
</p>

<p>
  <strong>BANGER:</strong><br>
  <%= @concert.media.html_safe %>
</p>


<%= link_to 'Edit', edit_concert_path(@concert) %> |
<%= link_to 'Back', concerts_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "BANGERS", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Concerts", concerts_path %></li>
        <li><%= link_to 'Add Concert', new_concert_path %></li>
        <li><%= link_to "About", about_path %></li>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>BANGERS</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	  <meta name="viewport" content="width=device-width, initial-scale=1.0">
	</head>
	<body>

		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |name, msg| %>
				<%= content_tag(:div, msg, class: "alert alert-info") %>
			<% end %>	
			<%= yield %>
		</div>
	</body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron center">
	<h1>About Us</h1>
	<p>Just trying to find some concerts where we can hear these BANGERS live.</p>
</div>

app/views/pages/home.html.erb
<div class="jumbotron center">
	<h1>The BANGERS Concert Calendar!</h1>
	<% if user_signed_in? %>
		<%= month_calendar events: @concerts do |date, concerts| %>
          <%= date %>

          <% concert.each do |concert| %>
            <div>
              <%= concert.name %>
            </div>
          <% end %>
        <% end %>
	<% else %>
		<p>
			<%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
			<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
		</p>
	<% end %>
</div>

app/views/pins/_form.html.erb
<%= form_for(@pin) do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<h1>Editing Pin</h1>
	</div>

	<div class="panel-body">
		<%= render 'form' %>
	</div>

	<div class="panel-footer">
		<%= link_to 'Show', @pin %> |
		<%= link_to 'Back', pins_path %>
	</div>
</div>

app/views/pins/index.html.erb
<h1>Listing Pins</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>User_id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pins.each do |pin| %>
      <tr>
        <td><%= pin.description %></td>
        <td><%= pin.user.email if pin.user %></td>
        <td><%= link_to 'Show | ', pin %></td>

        <% if pin.user == current_user %>
          <td><%= link_to 'Edit | ', edit_pin_path(pin) %></td>
          <td><%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pin', new_pin_path %>

app/views/pins/new.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<h1>New Pin</h1>
	</div>
	<div class="panel-body">
		<%= render 'form' %>
	</div>

	<div class="panel-footer">
		<%= link_to 'Back', pins_path %>
	</div>
</div>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @pin.description %>
</p>

<% if @pin.user == current_user %>
	<%= link_to 'Edit', edit_pin_path(@pin) %> |
<% end %>

<%= link_to 'Back', pins_path %>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day.mday) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day.mday, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day.mday, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day.mday, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <%= day.mday %>
                <% dailyConcerts = sorted_events.fetch(day, []) %>
                <% dailyConcerts.each do |concert| %>
                  <%= link_to concert.name, concert, style:'display: block;' %>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title">Week <%= start_date.strftime("%U").to_i %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>